import Head from "next/head";
import Link from "next/link";
const SucessPage = () => {
    return (
        <>
            <Head>
                <title>Magic Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

            </Head>
            <h1>Success page</h1>
            <Link href="/login">Login using magic link</Link>
        </>
    );
}

export default SucessPage;